// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageInfo() {
  return window['go']['app']['App']['GetImageInfo']();
}

export function LoadImage(arg1) {
  return window['go']['app']['App']['LoadImage'](arg1);
}

export function NextImage() {
  return window['go']['app']['App']['NextImage']();
}

export function OpenImage() {
  return window['go']['app']['App']['OpenImage']();
}

export function PreviousImage() {
  return window['go']['app']['App']['PreviousImage']();
}
