// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImageInfo():Promise<Record<string, any>>;

export function LoadImage(arg1:string):Promise<string>;

export function NextImage():Promise<string>;

export function OpenImage():Promise<string>;

export function PreviousImage():Promise<string>;
